title: "まっすたー (massuter) Official Site"
description: "VRChat配信や参加型配信を行う「まっすたー」の活動をまとめたサイト"
url: "https://your-username.github.io" # 実際のGitHub Pages URLに合わせて変更
baseurl: "" # ルートで運用する場合は空欄、リポジトリ名で運用する場合は"/repo-name"
lang: "ja"

# ビルド時に有効にしたいプラグイン
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-locale
  # i18n用プラグインなどがあれば追加

# ローカルホストでプレビューするときの設定
host: 0.0.0.0
port: 4000

# 追加のパラメータ例：OGP画像など
defaults:
  - scope:
      path: ""
    values:
      ogp_image: "/images/logo/logo-light.png"

# i18n（多言語対応）プラグインなどを使う場合の設定
locale_defaults:
  en:
    lang: "en"
  ja:
    lang: "ja"
