# Site settings
title: まっすたー (massuter) Official Site
email: your-email@example.com # Placeholder - Update later if needed
description: >- # this means to ignore newlines until "baseurl:"
  VRChat配信や参加型配信を行う配信者「まっすたー (massuter)」の活動を発信する公式サイト。
  SNS、動画、Note記事、画像ギャラリーなど多彩なコンテンツをお届けします。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://massuter.github.io" # the base hostname & protocol for your site
github_username: massuter

# Build settings
markdown: kramdown
# theme: minima # Removed as we are using a custom theme structure
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # Add other plugins like jekyll-multiple-languages-plugin later

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Ensure vrc-images are included in the build output
include:
  - vrc-images

# Default values for pages and posts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      lang: "ja" # Default language

# SEO/OGP Settings (using jekyll-seo-tag)
logo: /assets/images/logo/logo.png # Placeholder path
social:
  name: まっすたー (massuter)
  links:
    - https://x.com/Massuter
    - https://www.twitch.tv/massuter
    - https://www.youtube.com/@%E3%81%BE%E3%81%A3%E3%81%99%E3%81%9F%E3%83%BCm
    - https://vrchat.com/home/user/usr_aa99031d-1df4-4092-bde3-aef5af29596d
    - https://note.com/massuter

# i18n settings (Placeholder for jekyll-multiple-languages-plugin)
languages: ["ja", "en"]
default_lang: "ja"
exclude_from_localizations: ["assets/", "images/", "vrc-images/", "url-list.txt"]

# Custom variables (can be accessed via site.variable_name)
author:
  name: まっすたー
  id: massuter
