# --- Site Settings ---
title: まっすたー (massuter) Official Site # サイトタイトル
email: your-email@example.com # 連絡先メールアドレス (必要なら)
description: >- # サイトの説明 (SEO用)
  VRChat配信者「まっすたー (massuter)」の活動を発信する公式サイト。
  配信情報、Note記事、動画、画像ギャラリーなど。
baseurl: "" # サブディレクトリで公開しない場合は空
url: "https://massuter.github.io" # GitHub PagesのURL (カスタムドメインなら変更)
github_username: massuter # GitHubユーザー名

# --- Author Info ---
author:
  name: まっすたー
  id: massuter
  # 他のプロフィール情報もここに追加可能

# --- Build Settings ---
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# --- SEO Tag Settings (jekyll-seo-tag) ---
logo: /images/logo/logo-light.png # OGP画像などに使われるロゴ
social:
  name: まっすたー
  links:
    - https://x.com/Massuter
    - https://www.twitch.tv/massuter
    - https://www.youtube.com/@%E3%81%BE%E3%81%A3%E3%81%99%E3%81%9F%E3%83%BCm
    # 他のSNSプロファイルURL

# --- Language Settings (jekyll-multiple-languages-plugin の例) ---
# languages: ["ja", "en"] # 対応言語
# default_lang: "ja"      # デフォルト言語
# exclude_from_localizations: ["assets/", "images/", "vrc-images/"] # 翻訳対象外

# --- Collections (必要に応じて) ---
# collections:
#   portfolio:
#     output: true

# --- Defaults ---
defaults:
  - scope:
      path: "" # ルート
    values:
      layout: "default" # デフォルトレイアウト

# --- Sass ---
sass:
  sass_dir: assets/css
  style: compressed # compressed or expanded

# --- Exclude from processing ---
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt
  - .github
  - url-list.txt # Jekyllの処理対象外にする